export const referencePlaceableCatalogNames = [
  "Sprinkler", "Quality Sprinkler", "Iridium Sprinkler",
  "Wood Floor", "Stone Floor", "Weathered Floor", "Crystal Floor", "Straw Floor",
  "Gravel Path", "Wood Path", "Crystal Path", "Cobblestone Path", "Stepping Stone Path",
  "Brick Floor", "Rustic Plank Floor", "Stone Walkway Floor", "Tilled Dirt (Dry)",
  "Gate", "Hardwood Fence", "Wood Fence", "Stone Fence", "Iron Fence",
  "Grass Starter", "Blue Grass Starter",
  "Oak Tree (Normal)", "Maple Tree (Normal)", "Pine Tree (Normal)", "Palm Tree",
  "Mushroom Tree", "Mahogany Tree", "Palm Tree (2)", "Green Rain Tree (Oak) (Normal)",
  "Green Rain Tree (Maple) (Normal)", "Green Rain Tree (Mushroom)", "Mystic Tree",
  "Banana Tree (No Fruit)", "Cherry Tree (No Fruit)", "Apricot Tree (No Fruit)",
  "Orange Tree (No Fruit)", "Peach Tree (No Fruit)", "Pomegranate Tree (No Fruit)",
  "Apple Tree (No Fruit)", "Mango Tree (No Fruit)",
  "Scarecrow", "Lightning Rod", "Bee House", "Keg", "Furnace", "Preserves Jar",
  "Cheese Press", "Loom", "Oil Maker", "Recycling Machine", "Crystalarium",
  "Mayonnaise Machine", "Seed Maker", "Wood Sign", "Stone Sign", "Dark Sign", "Garden Pot",
  "Tall Torch", "Bonfire", "Bone Mill", "Feed Hopper", "Incubator", "Heater", "Tapper",
  "Camera", "Tub o' Flowers", "Rarecrow", "Rarecrow 2", "Charcoal Kiln", "Soda Machine",
  "Rarecrow 3", "Statue Of Endless Fortune", "Mushroom Box", "Chest", "Rarecrow 4",
  "Rarecrow 5", "Rarecrow 6", "Rarecrow 7", "Rarecrow 8", "Wooden Brazier (Lit)",
  "Stone Brazier (Lit)", "Gold Brazier (Lit)", "Campfire (Lit)", "Stump Brazier (Lit)",
  "Carved Brazier (Lit)", "Skull Brazier (Lit)", "Barrel Brazier (Lit)", "Marble Brazier (Lit)",
  "Wood Lamp-post", "Iron Lamp-post", "Worm Bin", "Slime Incubator", "Slime Egg-Press",
  "Statue Of Perfection", "Cask", "Auto-Grabber", "Deluxe Scarecrow", "Geode Crusher",
  "Workbench", "Mini-Jukebox", "Wood Chipper", "Telephone", "Mini-Fridge", "Item Pedestal",
  "Solar Panel", "Stone Chest", "Mini-Obelisk", "Farm Computer", "Coffee Maker",
  "Sewing Machine", "Mini-Shipping Bin", "Ostrich Incubator", "Junimo Chest", "Heavy Tapper",
  "Deconstructor", "Auto-Petter", "Hopper", "Campfire 2 (Lit)", "Statue Of True Perfection",
  "Text Sign", "Mushroom Log", "Bait Maker", "Dehydrator", "Heavy Furnace",
  "Statue Of Blessings", "Statue Of The Dwarf King", "Anvil", "Mini-Forge", "Fish Smoker",
  "Deluxe Worm Bin", "Big Chest", "Big Stone Chest", "Torch", "Drum Block", "Flute Block",
  "Crab Pot", "Jack-O-Lantern", "Tea Sapling", "Large Stump", "Large Log", "Meteorite",
  "Large Boulder", "Mannequin (Male)", "Mannequin (Female)", "Cursed Mannequin (Male)",
  "Cursed Mannequin (Female)",
] as const;
